In [8]:
import os
import pandas as pd

In [2]:
in_dir = r"/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations"

In [11]:
in_csvs = [os.path.join(in_dir, f) for f in os.listdir(in_dir) if f.endswith('.csv')]

In [12]:
in_csvs

['/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/HI_final_annotations.csv',
 '/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/KA_final_annotations.csv',
 '/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/KO_final_annotations.csv',
 '/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/LA_final_annotations.csv',
 '/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/MA_final_annotations.csv',
 '/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/MO_final_annotations.csv',
 '/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/NI_final_annotations.csv',
 '/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/OA_final_annotations.csv']

In [13]:
merged_csvs = pd.concat([pd.read_csv(f) for f in in_csvs])

In [14]:
merged_csvs

,filename,x_min,y_min,x_max,y_max,px_x_min,px_y_min,px_x_max,px_y_max,label_name,label,label_int
0,hawaii_1_10158_12_85,281130.173489,2.188318e+06,281132.173489,2.188320e+06,390.0,117.0,491.0,217.0,other,O,10
1,hawaii_1_10158_10_86,281119.905495,2.188312e+06,281120.905495,2.188313e+06,384.0,90.0,434.0,140.0,metal,M,4
2,hawaii_1_10158_10_87,281117.121801,2.188308e+06,281118.121801,2.188309e+06,243.0,110.0,294.0,160.0,other,O,10
3,hawaii_1_10158_12_87,281127.708464,2.188308e+06,281128.708464,2.188309e+06,266.0,109.0,316.0,159.0,plastic,P,6
4,hawaii_1_10438_18_50,281061.619813,2.189540e+06,281063.619813,2.189542e+06,215.0,46.0,316.0,146.0,tire,T,7
...,...,...,...,...,...,...,...,...,...,...,...,...
988,oahu_3_7149_17_54,606953.106605,2.400850e+06,606957.106605,2.400854e+06,130.0,38.0,328.0,239.0,processed wood,W,8
989,oahu_3_7149_23_59,606987.242274,2.400829e+06,606988.242274,2.400830e+06,282.0,241.0,331.0,291.0,cloth,C,1
990,oahu_3_7149_27_66,607010.990835,2.400789e+06,607011.990835,2.400790e+06,432.0,31.0,482.0,81.0,buoy,B,0
991,oahu_3_7149_32_72,607033.218823,2.400760e+06,607034.218823,2.400761e+06,251.0,111.0,301.0,161.0,plastic,P,6
992,oahu_3_7149_35_74,607048.813797,2.400748e+06,607049.813797,2.400749e+06,255.0,38.0,304.0,88.0,plastic,P,6

In [19]:
#reversing an error in retile_for_dl that did not take into account that geographic software uses a bottom-left origin, and deep learning software uses
#a top left origin.

merged_csvs['new_px_y_max'] = 512 - merged_csvs['px_y_min']
merged_csvs['new_px_y_min'] = 512 - merged_csvs['px_y_max']

In [20]:
merged_csvs

,filename,x_min,y_min,x_max,y_max,px_x_min,px_y_min,px_x_max,px_y_max,label_name,label,label_int,new_px_y,new_px_y_min,new_px_y_max
0,hawaii_1_10158_12_85,281130.173489,2.188318e+06,281132.173489,2.188320e+06,390.0,117.0,491.0,217.0,other,O,10,395.0,295.0,395.0
1,hawaii_1_10158_10_86,281119.905495,2.188312e+06,281120.905495,2.188313e+06,384.0,90.0,434.0,140.0,metal,M,4,422.0,372.0,422.0
2,hawaii_1_10158_10_87,281117.121801,2.188308e+06,281118.121801,2.188309e+06,243.0,110.0,294.0,160.0,other,O,10,402.0,352.0,402.0
3,hawaii_1_10158_12_87,281127.708464,2.188308e+06,281128.708464,2.188309e+06,266.0,109.0,316.0,159.0,plastic,P,6,403.0,353.0,403.0
4,hawaii_1_10438_18_50,281061.619813,2.189540e+06,281063.619813,2.189542e+06,215.0,46.0,316.0,146.0,tire,T,7,466.0,366.0,466.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,oahu_3_7149_17_54,606953.106605,2.400850e+06,606957.106605,2.400854e+06,130.0,38.0,328.0,239.0,processed wood,W,8,474.0,273.0,474.0
989,oahu_3_7149_23_59,606987.242274,2.400829e+06,606988.242274,2.400830e+06,282.0,241.0,331.0,291.0,cloth,C,1,271.0,221.0,271.0
990,oahu_3_7149_27_66,607010.990835,2.400789e+06,607011.990835,2.400790e+06,432.0,31.0,482.0,81.0,buoy,B,0,481.0,431.0,481.0
991,oahu_3_7149_32_72,607033.218823,2.400760e+06,607034.218823,2.400761e+06,251.0,111.0,301.0,161.0,plastic,P,6,401.0,351.0,401.0
992,oahu_3_7149_35_74,607048.813797,2.400748e+06,607049.813797,2.400749e+06,255.0,38.0,304.0,88.0,plastic,P,6,474.0,424.0,474.0

In [ ]:
merged_csvs.to_csv(r"/media/ross/ssd/00_data/20191205_HI_2015_coastalimagery_dl/annotations/ALL_final_annotations_20191214.csv")